account-service|../system-graph-account-service|https://github.com/Diegobraun/system-graph-account-service.git
loan-service|../system-graph-loan-service|https://github.com/Diegobraun/system-graph-loan-service.git
