account-service|../system-graph-account-service|https://github.com/Diegobraun/system-graph-account-service.git|8081
loan-service|../system-graph-loan-service|https://github.com/Diegobraun/system-graph-loan-service.git|8082
customer-service|../system-graph-customer-service|https://github.com/Diegobraun/system-graph-customer-service.git|8083
payment-service|../system-graph-payment-service|https://github.com/Diegobraun/system-graph-payment-service.git|8084
notification-service|../system-graph-notification-service|https://github.com/Diegobraun/system-graph-notification-service.git|8085
investment-service|../system-graph-investment-service|https://github.com/Diegobraun/system-graph-investment-service.git|8086
fraud-service|../system-graph-fraud-service|https://github.com/Diegobraun/system-graph-fraud-service.git|8087
